version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8080"
    environment:
      - DB_CONNECTION_STRING=postgres://u_tzt623sgywyqhd6:rekphmlozh3ce6g@02f7e6f1-1adb-4347-835a-02c74fcccb0e.db.cloud.postgresml.org:6432/pgml_m0rkbxzq1ewj2de
     
    depends_on:
      - db

  user-service:
    build: ./user-service
    ports:
      - "8082:8080"
    environment:
      - DB_CONNECTION_STRING=postgres://u_tzt623sgywyqhd6:rekphmlozh3ce6g@02f7e6f1-1adb-4347-835a-02c74fcccb0e.db.cloud.postgresml.org:6432/pgml_m0rkbxzq1ewj2de
    depends_on:
      - db

  profile-service:
    build: ./profile-service
    ports:
      - "8083:8080"

    environment:
      - DB_CONNECTION_STRING=postgres://u_tzt623sgywyqhd6:rekphmlozh3ce6g@02f7e6f1-1adb-4347-835a-02c74fcccb0e.db.cloud.postgresml.org:6432/pgml_m0rkbxzq1ewj2de
     
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservices
    ports:
      - "6432:6432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

